### ISSUE TITLE
[Feature request] Provide macOS builds on GitHub 

### ISSUE THREAD

**Issue by shinra-electric** [tsalvo/nes-emu-ios#115]
I have no issue building a catalyst version myself, but most people I know wouldn’t know how to do that.

**Comment by tsalvo** [comment]
This is a good idea. I can do this the next time a new commit goes into the master branch. Or maybe this weekend when I get some time, I can just make a tag at the current master commit, along with a release, and upload a binary.

**Comment by tsalvo** [comment]
I tagged a `0.0.1` release for the current master branch!  Every once in a while, when master changes significantly enough, I plan to keep creating new macOS Catalyst release builds
