### ISSUE TITLE
ipa release for trollstore ?

### ISSUE THREAD

**Issue by Q191** [tsalvo/nes-emu-ios#131]

**Comment by Q191** [comment]
build a ipa, but not works well.

Uploading 2023_12_30_23_33_IMG_3084.MP4…

**Comment by tsalvo** [comment]
Make sure that you build for Release mode, using the "nes-emu-iOS Release" scheme

**Comment by Q191** [comment]
> Make sure that you build for Release mode, using the "nes-emu-iOS Release" scheme. It should run at full speed then.
> 
> If you publish an IPA to the trollstore, I would ask that you please add a link to this GitHub repository. It's not strictly required due the the MIT license, so you're free to do what you want either way 🙂

Got it.

**Comment by Q191** [comment]
> > Make sure that you build for Release mode, using the "nes-emu-iOS Release" scheme. It should run at full speed then.
> > If you publish an IPA to the trollstore, I would ask that you please add a link to this GitHub repository. It's not strictly required due the the MIT license, so you're free to do what you want either way 🙂
> 
> Got it.

[nes-1.0.ipa.zip](https://github.com/tsalvo/nes-emu-ios/files/13798819/nes-1.0.ipa.zip)

![image](https://github.com/tsalvo/nes-emu-ios/assets/83848311/3847f7f2-b417-46c4-8344-61a42bd0ff45)

Works now, randomly return home when using controllers though.

**Comment by tsalvo** [comment]
Thanks! I'll check into the controller issue. Apple may have changed something with the GameController Framework

**Comment by tsalvo** [comment]
I'm not having this issue with my setup. I'm using iOS 17.2.1 on an iPhone 15 Pro, paired with a PS5 DualSense controller.

What is your setup like?
