### ISSUE TITLE
Hash set filtering

### ISSUE THREAD

**Issue by upintheairsheep** [tsalvo/nes-emu-ios#132]
This app was recently pulled from the App Store in fear. To prevent piracy and allow the app on the App Store again, implement a hash-set containing all commercially released NES games, and on the App Store version, when a pirated (or legally dumped) ROM is uploaded, to prevent piracy, an anti-piracy screen comes up, and if a homebrew game is loaded, it will run. The emulator can then be uploaded back onto the App Store. This change should be on a separate branch for the App Store release, as GitHub compilers and users are more likely to have a device to dump legally obtained cartridges. To get the hash list, contact NO-INTRO on Discord, a collective that privately has an archive of cartridge games.

**Comment by tsalvo** [comment]
Thank you for the good suggestion. There might still be some slightly-modified-but-not-broken ROMs that would make it through, but the app would at least be making a reasonable effort to prevent it. 

I don't plan on releasing it again, but I do appreciate the suggestion

**Comment by upintheairsheep** [comment]
Why won’t you re-release it, if there is no piracy problem, there is no
DRM-breaking that emulators that target newer consoles use.

**Comment by tsalvo** [comment]
I know that technically you're right, and it shouldn't be an issue. I'm sorry to have let you and others down.

**Comment by tsalvo** [comment]
Also, that's not to say someone else couldn't take this code and try to release it themselves. It's a very permissive MIT license. I just realized after today that I really, really don't want to be that person

**Comment by TCB13** [comment]
@tsalvo thank you for the initial release on the App Store. I understand your fears and while I believe @upintheairsheep suggestion makes the emulator very useless I also know that there are other emulators on the App Store that do what your does and aren't banned.

To be fair, I was perfectly fine with paying 10$ for your emulator on the App Store, just so it could be accessible from any iOS device and will be updated in the future.

I know this has some legal details, but you aren't providing ROMs so no copyright infringement, if it goes bad in some way, well, Apple takes it down and we all move on.

I hope you reconsider your position and offer this on the App Store again. Thank you.
