### ISSUE TITLE
Someone apparently flipped your emulator on the AppStore, it is called iNES

### ISSUE THREAD

**Issue by LucidSnow** [tsalvo/nes-emu-ios#134]
https://apps.apple.com/us/app/ines-nes-emulator-retro-emu/id6499447166 

So I'm pretty sure Bimmy would be fine to rerelease

You might want to get the asset flip taken down though

**Comment by tsalvo** [comment]
Maybe I was very hasty in pulling the app, especially after Delta literally came out the day after 😅  I'll think about doing another Bimmy release someday, but with Delta, I feel like everyone's needs are being met really well with that. I might want to make more improvements first anyway 🙂

This iNES app actually seems ok to me, even if they are using some of my code (not 100% sure if they are), it looks like they've changed up quite a few things. They don't appear to be doing any tracking or anything scammy. And this codebase has a very permissive MIT license - it's free to take this code and do what you please, so I would really only complain if the app was using this code and also doing something really scammy on top of that.

**Comment by LucidSnow** [comment]
> Maybe I was very hasty in pulling the app, especially after Delta literally came out the day after 😅  I'll think about doing another Bimmy release someday, but with Delta, I feel like everyone's needs are being met really well with that. I might want to make more improvements first anyway, now that the bar is set really high 🙂
> 
> This iNES app actually seems ok to me, even if they are using some of my code (not 100% sure if they are), it looks like they've changed up quite a few things. They don't appear to be doing any tracking or anything scammy. And this codebase has a very permissive MIT license - it's free to take this code and do what you please, so I would really only complain if the app was using this code and also doing something really scammy on top of that.

Absolutely agree

Only problem is the same guy made a gba4ios bootleg the same way, a complete rip with mainly cosmetic changes

He did it before, never gave credit, and got popular off of it, that is what I was trying to point out
