### ISSUE TITLE
Nes Emu Issue

### ISSUE THREAD

**Issue by DzaminNayura** [tsalvo/nes-emu-ios#136]
Sorry to use this msg board to contact you, but I couldn't find your email everywhere I googled and github discussions aren't enabled here for some reason.
There is a clone of your emulator called eNes on the appstore.
https://apps.apple.com/us/app/enes-nes-emulator-retro-emu/id6499447166

As I understand, you took Bimmy down due to it receiving too much attention, which may be risky for you.
(https://forums.macrumors.com/threads/nes-emulator-for-iphone-and-ipad-now-available-on-app-store-removed.2424326/page-2?post=33074585#post-33074585)

The creator of your clone (eNES) on the appstore (Mattia La Spina) was involved in a previous controversy whereby he added ads (banner and pop up), trackers,  to his now removed copycat emulator, iGBA which pissed off a lot of people. (https://www.macrumors.com/2024/04/15/apple-further-explains-igba-removal/)

He was also forced to change the name of his app from iNes to eNes, probably from some other dev DMCAing him.
You may wish to contact Apple and issue a DMCA takedown before this clone attracts unnecessary attention to you and your repositories and ends up being risky for you.

Thank you.

**Comment by tsalvo** [comment]
Thanks for the heads up! Someone else had also let me know about this app when it was named iNES, and the history of the developer's actions with the GBA emulator. I'm inclined to leave it alone for now. There may not be a whole lot I can do anyway unless eNES is doing something really scammy or is breaking some App Store rules. This repo has a very permissive MIT license, so there's not much stopping any dev from taking this code and releasing it. 

With Delta being such a great free option that does no tracking, I think things are different now - no one would want to use eNES if he suddenly made it worse. 

I'm not too worried about attention on the GitHub repo and may even try to release Bimmy again in the future. But now that the bar is set way higher with Delta, I'm not happy enough with it to release it as-is 🙂 I'll keep an eye out for eNES and let Apple know if the dev seems to have added anything malicious on top of it. I appreciate the heads up!
